export const GinoWorks = {
  apps: [
    {
      name: "Administración de clientes",
      src: "../portafolio/logos/administrator.png",
      alt: "administrador de clientes crud",
      text: "Un panel de administración en donde se agregan, modifican y eliminan clientes de un sistema de datos",
      code: "React.js + Vite + Tailwind CSS + Database: JSON Server",
      url: "https://administrador-de-clientes.vercel.app",
    },
    {
      name: "Gastos y presupuestos",
      src: "../portafolio/logos/gastapp.png",
      alt: "app de gastos y presupuestos",
      text: "App que sirve para calcular gastos y presupuesto general",
      code: "React.js (create-react-app) + Short ID",
      url: "https://presupuesto-app-psi.vercel.app/",
    },
    {
      name: "Administración de turnos",
      src: "../portafolio/logos/turnon.png",
      alt: "app de turnos",
      text: "App para agendar y administrar turnos, adaptable a cualqueir negocio",
      code: "React.js + Database: Local Storage",
      url: "https://administrador-de-turnos.vercel.app/",
    },
    {
      name: "Cotizador de Cripto$",
      src: "../portafolio/logos/cotizacripto.png",
      alt: "app de criptomodenas",
      text: "Aplicación web que cotiza criptomonedas a través de una API",
      code: "React.js + Emotion Styled Components + Axios (para consumir la API)",
      url: "https://cotizacripto.vercel.app/",
    },
    {
      name: "Información del clima",
      src: "../portafolio/logos/climapp.png",
      alt: "app de clima",
      text: "Aplicación de clima donde el usuario ingresa ciudad y país, y esta entrega datos del clima",
      code: "React.js + Materialize CSS + Fetch (para consumir la API)",
      url: "https://climapp-green.vercel.app/",
    },
    {
      name: "Frases Breaking Bad",
      src: "../portafolio/logos/breakingbad.png",
      alt: "app de frases de breaking bad",
      text: "Frases de Breaking Bad obtenidas aleatoriamente",
      code: "React.js + Emotion Styled Components + Fetch (para consumir la API)",
      url: "https://breakingbad-beige.vercel.app/",
    },
    {
      name: "App Cotizador de Seguros",
      src: "../portafolio/logos/cotizaya.png",
      alt: "seguros cotizacion",
      text: "Cotizador de seguros, donde recibiendo diferentes parámetros calcula el precio del seguro seleccionado",
      code: "React.js + Emotion Styled Components",
      url: "https://cotizador-seguro.vercel.app/",
    },
    {
      name: "Invitación Cumpleaños",
      src: "../portafolio/logos/cumple.png",
      alt: "invitacion qr",
      text: "Invitación a cumpleaños luego de escanear un código QR",
      code: "React.js + Vite + QR Code",
      url: "https://invitacion-valentina.vercel.app/",
    },
  ],
  empresas: [
    
    {
      name: "CriptoBeer",
      src: "../portafolio/logos/criptobeer.png",
      alt: "criptobeer web page",
      text: "Emprendimiento mendocino de cerveza artesanal",
      code: "React.js + Vite + Tailwind CSS",
      url: "https://criptobeer.ar",
    },
    {
      name: "Cercos Permietrales SN",
      src: "../portafolio/logos/sannicolas.png",
      alt: "cercos san nicolas web page",
      text: "Empresa de cercos perimetrales y construcción en general",
      code: "React.js + Next.js + Tailwind CSS",
      url: "https://cercosperimetralesyservicios-sn.com.ar",
    },
    {
      name: "Citroaventura",
      src: "../portafolio/logos/citroaventura.webp",
      alt: "citroaventura",
      text: "Web de aventureros recorriendo el mundo en su Citroen 3CV",
      code: "React.js + Next.js + Tailwind CSS",
      url: "https://cercosperimetralesyservicios-sn.com.ar",
    },
    {
      name: "Técnicos Ya",
      src: "../portafolio/logos/tecnicosya.png",
      alt: "tecnicos ya",
      text: "Web de empresa de tecnología",
      code: "React.js + Next.js + Tailwind CSS + React Reveal (Scroll animations)",
      url: "https://www.tecnicosya.com.ar/",
    },
    {
      name: "Powersis Tecnología",
      src: "../portafolio/logos/powersis.png",
      alt: "powersis web page",
      text: "Empresa mendocina de tecnología (Mi primer web para un cliente)",
      code: "HTML + CSS + JQuery + PHP (formulario de contacto)",
      url: "https://powersis.com.ar",
    },
    
    {
      name: "Web App para Abogados",
      src: "../portafolio/logos/abogados.png",
      alt: "app abogados ",
      text: "Proyecto de Web App velóz para servicios de abogacía, ofreciendo servicios gratuitos y pagos",
      code: "React.js + Next.js + Tailwind CSS + Prismic CMS (Adminsitrador de contenido)",
      url: "https://abogados-app.vercel.app/",
    },

    {
      name: "Carta QR para bares",
      src: "../portafolio/logos/cartaqr.png",
      alt: "carta qr bar restaurant",
      text: "Proyecto de una Carta web, completa, con más opciones y personalización, súper rápida y administrable por el cliente",
      code: "React.js + Next.js + Tailwind CSS + Prismic CMS (Adminsitrador de contenido)",
      url: "https://ejemplo-carta-qr.vercel.app",
    }
  ],
  proyectos: [
    {
      name: "Dev Zeppelin Software",
      src: "../portafolio/logos/devzeppelin.webp",
      alt: "gestoría de software y diseño dev zeppelin",
      text: "Proyecto personal de gestoría de software y diseño",
      code: "React.js + Next.js + Tailwind CSS",
      url: "https://devzeppelin.com.ar",
    },
    {
      name: "Moonblog",
      src: "../portafolio/logos/moonblog.png",
      alt: "moonblog blog personal de moonwatcher",
      text: "Blog personal donde publico ideas y artículos de interés general",
      code: "React.js + Next.js + Tailwind CSS + Prismic CMS (Adminsitrador de contenido)",
      url: "https://moonblog.ar",
    },
    {
      name: "Escuela de programación",
      src: "../portafolio/logos/codeobrero.webp",
      alt: "code obrero escuela de programacion by moonwatcher",
      text: "Mis consejos útiles para orientar en sus primeros pasos a quién quiera comenzar a estudiar programación",
      code: "React.js + Next.js + Styled JSX",
      url: "https://code-obrero.vercel.app/",
    },
    {
      name: "Catálogo de cabañas",
      src: "../portafolio/logos/winehouse.png",
      alt: "winehouse cañas mendoza",
      text: "Catálogo para promocionar cabañas donde el usuario encuentra información como el precio del dólar, o el clima",
      code: "React.js + Vite + Tailwind CSS",
      url: "https://winehouse.vercel.app",
    }

  ],
  proyectosOld: [
    {
      name: "Mi primer portfolio",
      src: "../portafolio/logos/ginoweb.png",
      alt: "antiguo portfolio gino pietrobon",
      text: "Mi primer portfolio cuando empecé a estudiar programación",
      code: "HTML + CSS + JQuery + PHP",
      url: "https://devzeppelin.github.io/ginitopage/",
    },
    {
      name: "Invitaciones Web",
      src: "../portafolio/logos/invitaweb.png",
      alt: "invitaciones web gino pietrobon",
      text: "Proyecto para realizar invitaciones a eventos, estilo página web",
      code: "HTML + CSS + JavaScript",
      url: "https://devzeppelin.github.io/InvitacionWeb/",
    },
    {
      name: "Gráficos con HTML y CSS",
      src: "../portafolio/logos/css.png",
      alt: "graphics css html gino pietrobon",
      text: "Realizando gráficos en movimiento con CSS y JavaScript",
      code: "HTML + CSS + JavaScript",
      url: "https://devzeppelin.github.io/graphics-with-css-and-javascript/index.html",
    },
  ],
};
